language: node_js
node_js: stable
cache:
    apt: true
    directories:
        - node_modules
sudo: required
git:
    quiet: true
install:
    - sudo apt-get install -y sshpass
script:
    - pwd
    - ls -a
    - export K8S_VERSION="v1.15.3"
    - export K8S_DIR="d8sdir"
    - mkdir ${K8S_DIR}
    - wget -c -q https://dl.k8s.io/${K8S_VERSION}/kubernetes-server-linux-amd64.tar.gz -P ${K8S_DIR}
    - wget -c -q https://dl.k8s.io/${K8S_VERSION}/kubernetes-client-linux-amd64.tar.gz -P ${K8S_DIR}
    - wget -c -q https://dl.k8s.io/${K8S_VERSION}/kubernetes-node-linux-arm64.tar.gz -P ${K8S_DIR}
    - ls -a
    #- chmod +x *.sh
    #- ./get-kube.sh
    # 此处进行编译、构建等操作
    

after_script:
    # 此处进行部署等操作
    - echo "after script..."
    - echo "ssh check" > file.txt # 临时文件
    - sshpass -p "${PASSWD}" ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "uname -a > /tmp/foo"
    - sshpass -p ${PASSWD} scp -o StrictHostKeyChecking=no file.txt ${USER}@${HOST}:/tmp/
    - echo $?
    - echo "copying files to server"
    - sshpass -p ${PASSWD} scp -o StrictHostKeyChecking=no -r ${K8S_DIR} ${USER}@${HOST}:/tmp/
    #- echo $?